### ISSUE TITLE
block comments not recognized

### ISSUE THREAD

**Issue by jhidding** [sjhuangx/vscode-scheme#1]
Hi,
R6RS scheme has syntax for (nestable) block comments
#| like this
  |#
But these comments are not recognized by the plugin.
Cheers, Johan

**Comment by dmeleshko** [comment]
@sjhuangx 
I made pull request that fixing this issue, please accept it.

**Comment by tinyjiahao** [comment]
@dmeleshko Thank you very much!
I accept it and have publish to vscode marketplace.

**Comment by jhidding** [comment]
I can't see the update yet, seeing version 3.2.0 in vscode, but comments are still not highlighted.
