### ISSUE TITLE
I'm a beginner -- How do I compile my Scheme script

### ISSUE THREAD

**Issue by thecodingconductor** [sjhuangx/vscode-scheme#6]
Hello, 

I am a programming beginner and have been slowly working my way through SICP. I have installed the Scheme extension to Visual Studio Code successfully. How do I compile my Scheme code via the command line? Sorry for the super noob question. 

Best,
Tristan

**Comment by johnzhu12** [comment]
I only know how to run the  code from terminal ,FYI
1. enter 'scheme' to enter the scheme interactive console
2. enter 
 > (load 'hello.scm')

**Comment by tinyjiahao** [comment]
you should use the terminal to compile your scheme script, first enter scheme interactive, then use (load "/path/to/script"), then script will load into interperter
